# Generated by Django 4.0.5 on 2022-06-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_manageent_system_app', '0004_teachers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_start', models.CharField(max_length=100)),
                ('session_end', models.CharField(max_length=100)),
            ],
        ),
    ]
